version: "3.6"

services:
  jira:
    restart: always
    container_name: jira
    network_mode: host
    build: . 
    ports:
    - 8085:8080
    volumes:
    - /home/pi/IOTStack/volumes/jira:/var/atlassian/jira
    - /var/run/docker.sock:/var/run/docker.sock
